### ISSUE TITLE
SimpleProgram: do you mean f or g in line 6?

### ISSUE THREAD

**Issue by Dierk** [psurkov/intellij-frege#22]
https://github.com/psurkov/intellij-frege/blob/6649b9654c59f659a5cdb33e815e1ef4def4b13b/src/test/testData/parsing/validPrograms/SimpleProgram.fr#L6

**Comment by psurkov** [comment]
Hi, it's a part of parsing tests. We just want to test that file is parsing correctly and PSI tree is built without errors, so we don't have to care about the contents of the program.
